### PR TITLE
Implement order dependent time between two times

### PR DESCRIPTION
**Pull request by Kobe-Kwanten**
Implement order dependent time between two times.

Time is calculated over midnight.
`20:00:00 - 03:00:00 results in 7 hours (4 hours until midnight + 3 hours)`
`20:00:00 - 03:00:00 results in 420 minutes (4 hours until midnight + 3 hours)`
`20:00:00 - 03:00:00 results in 25200 seconds (4 hours until midnight + 3 hours)`

@stephenhenckaerts  this is what you requested?

### CODE REVIEW

**Comment by Kobe-Kwanten** [comment]
For the record, not a fan of implenting this and I don't think we want to.
I think you have a modelling issue in which you confuse a time with a date time.

**Comment by Kobe-Kwanten** [comment]
For refrence see how PSQL handles this:

```
SELECT '10:00:00'::time - '02:00:00'::TIME; -- 08:00:00
SELECT '02:00:00'::time - '10:00:00'::TIME; -- -08:00:00
```

**Comment by jorenvandeweyer** [comment]
Zeer interessant om te zien hoe postgres dat afhandelt 🤔 

Wat is uw use case? @stephenhenckaerts 

@Kobe-Kwanten Hoe zijt gij het in Trixxa aangepakt hebben moesten de huishoudhulp toch 's nachts gaan kuisen?

**Review by jorenvandeweyer — COMMENTED** [review]
Zeer interessant om te zien hoe postgres dat afhandelt 🤔

Wat is uw use case? @stephenhenckaerts

@Kobe-Kwanten Hoe zijt gij het in Trixxa aangepakt hebben moesten de huishoudhulp toch 's nachts gaan kuisen?

**Pull request closed without merging**
